### ISSUE TITLE
Titles Repeating In Customizer

### ISSUE THREAD

**Issue by louisblythe** [elevate360/Atlantic#5] opened 2016-09-20 03:12 UTC
The titles of the font section are all the same when you open the latest version of Atlantic in the WordPress customiser.
<img width="293" alt="screen shot 2016-09-20 at 10 50 06 am" src="https://cloud.githubusercontent.com/assets/3523701/18656366/ea27c3ee-7f33-11e6-88cf-21bd9ede26a8.png">

**Comment by simonrcodrington** [comment] 2016-09-20 03:21
I noticed this today and the issue is trying to make those strings "Localised" e.g translatable. 

All the settings still work but just have the same name. 

I'll look at finding a solution (e.g maybe dumping translations for those strings) to get it to work again

**Comment by simonrcodrington** [comment] 2016-09-27 08:10
Hey @louisblythe  this has been fixed in version 1.1.5. Thought I'd fix it before the next major version.

**Closed** 2016-09-27 08:11 UTC
Labels: bug
